import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.scss'

export default function History() {
  const today = new Date();
  const yy = today.getFullYear();
  const mm = today.getMonth() + 1;
  const dd = today.getDay();

  return (
    <div className={styles.container}>
      <Head>
        <title>darakeee.dev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to My site!
        </h1>
        <div className={styles.history}>
            <section className={styles.menu}>
                <Link href="/"><h3>Profile</h3></Link>
                <h2>History</h2>
            </section>
            <section className={styles.detail}>
              <ul className={styles.timeline}>
                <li>
                  <p className={styles.timelineDate}>1999/11/11</p>
                  <div className={styles.timelineContent}>
                    <h3>Born in Nagoya:D</h3>
                  </div>
                </li>
                <li>
                  <p className={styles.timelineDate}></p>
                  <div className={styles.timelineContent}>
                    <h3>Now.</h3>
                  </div>
                </li>
              </ul>    
            </section>
        </div> 
      </main>

      <footer className={styles.footer}>
        <p>Copyright © 2022 darakeee.</p>
      </footer>
    </div>
  )
}
