import Head from 'next/head'
import styles from '../styles/Home.module.scss'

//svg
import Twi from '../public/twitter.svg'
import GH from '../public/github.svg'


export default function History() {
  return (
    <div className={styles.container}>
      <Head>
        <title>darakeee.dev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to My site!
        </h1>
        <div className={styles.history}>
            <section className={styles.menu}>
                <h3>Profile</h3>
                <h2>History</h2>
            </section>
            <section className={styles.detail}>    
            </section>
        </div> 
      </main>

      <footer className={styles.footer}>
        <p>Copyright © 2022 darakeee.</p>
      </footer>
    </div>
  )
}
