import Head from 'next/head'
import styles from '../styles/Home.module.scss'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>darakeee.dev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to My site!
        </h1>
        <div className={styles.profile}>
            <section className={styles.profileTitle}>
                <h2>My profile</h2>
            </section>
            <section className={styles.detail}>
                <h3>darakeee</h3>
                <p>Yuto Torii</p>
                <h4>Birth day</h4>
                <p>1999/11/11</p>
            </section>
            <section className={styles.skills}>
                <h4>Skils</h4>
            </section>
            <section className={styles.learn}>
                <h4>Learn</h4>
            </section>
        </div> 
      </main>

      <footer className={styles.footer}>
        <p>Copyright © 2021 darakeee.</p>
      </footer>
    </div>
  )
}
